USE rxt1077;

CREATE TABLE IF NOT EXISTS user (
    first VARCHAR(255) NOT NULL,
    last VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    hash CHAR(60) NOT NULL,
    emailConfirmed BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (email)
);

CREATE TABLE IF NOT EXISTS portfolio (
    id INTEGER NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    cash DECIMAL(13,2) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS stock (
    portfolio_id INTEGER NOT NULL,
    symbol VARCHAR(255) NOT NULL,
    shares INTEGER NOT NULL,
    PRIMARY KEY (portfolio_id, symbol)
);

CREATE TABLE IF NOT EXISTS log (
    datetime DATETIME NOT NULL,
    portfolio_id INTEGER NOT NULL,
    action VARCHAR(255) NOT NULL,
    symbol VARCHAR(255) NOT NULL,
    shares INTEGER NOT NULL,
    price DECIMAL(13,2) NOT NULL
);
